import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Part } from "@google/genai";

const app = express();
const PORT = 3000;

// Setup JSON body parsing with large limit for image transfers
app.use(express.json({ limit: "50mb" }));
app.use(express.urlencoded({ limit: "50mb", extended: true }));

// Initialize GoogleGenAI client with server secret key
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      "User-Agent": "aistudio-build",
    },
  },
});

// Health check
app.get("/api/health", (req, res) => {
  res.json({ status: "ok" });
});

// API endpoint: Extraction Event Info
app.post("/api/gemini/extract", async (req, res) => {
  const { fileBase64, mimeType } = req.body;
  if (!fileBase64 || !mimeType) {
    res.status(400).json({ error: "Missing file base64 or mime type" });
    return;
  }

  const filePart: Part = {
    inlineData: {
      data: fileBase64,
      mimeType: mimeType,
    },
  };

  const prompt = `
    Bạn là một trợ lý AI chuyên trích xuất thông tin sự kiện từ các tài liệu hoặc hình ảnh thư mời.
    Hãy phân tích file đính kèm và trích xuất các thông tin sau dưới dạng JSON:
    - eventName, eventType, date, time, targetAudience
    - eventFormat, onlinePlatform, offlineAddress
    - dressCode, contactName, contactPhone, contactEmail
    Trả về định dạng JSON thuần túy.
  `;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash", // upgraded engine as requested
      contents: [filePart, { text: prompt }],
      config: { responseMimeType: "application/json" },
    });

    const text = response.text;
    if (!text) {
      throw new Error("No text response received from extraction model");
    }

    const data = JSON.parse(text);
    res.json(data);
  } catch (error) {
    console.error("Extraction API Error:", error);
    res.status(500).json({ error: (error as Error).message });
  }
});

// API endpoint: Background Cleaning
app.post("/api/gemini/clean-background", async (req, res) => {
  const { imageBase64, mimeType } = req.body;
  if (!imageBase64 || !mimeType) {
    res.status(400).json({ error: "Missing image base64 or mime type" });
    return;
  }

  const imagePart: Part = {
    inlineData: {
      data: imageBase64,
      mimeType: mimeType,
    },
  };

  const prompt = "Recreate the BACKGROUND ONLY. Remove text, logos, people. Keep colors/shapes.";

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash-image",
      contents: [imagePart, { text: prompt }],
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        res.json({
          imageUrl: `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`,
        });
        return;
      }
    }
    throw new Error("No background image generated by image model.");
  } catch (error) {
    console.error("Clean Background API Error:", error);
    res.status(500).json({ error: (error as Error).message });
  }
});

// API endpoint: Poster Generation
app.post("/api/gemini/generate-poster", async (req, res) => {
  const {
    formData,
    backgroundPart,
    logoParts,
    speakerParts,
    qrCodePart,
    defaultLogoPart,
  } = req.body;

  if (!formData) {
    res.status(400).json({ error: "Missing event form data" });
    return;
  }

  const parts: Part[] = [];

  // 1. Analyze Topics for Imagery Rules
  const topics = formData.themeTopics.join(" ").toLowerCase();
  const isTech =
    topics.includes("công nghệ") ||
    topics.includes("tech") ||
    topics.includes("ai") ||
    topics.includes("số");

  let backgroundVisuals = "";
  let forbiddenVisuals = "Messy cluttered text, distorted faces, low resolution.";

  if (isTech) {
    backgroundVisuals = `
      **THEME: HIGH-TECH & AI**
      - **Background Elements:** 3D Microchips, Glowing Circuit Board Traces, Fiber Optic data streams, Metallic textures, Abstract nodes connecting.
      - **Hero Object (Optional):** A sleek, modern Humanoid Robot hand or silhouette, or a floating 3D Processor Chip.
      - **NEGATIVE PROMPT (FORBIDDEN):** DO NOT USE HUMAN BRAINS. DO NOT USE BIOLOGICAL ANATOMY. DO NOT USE OLD-SCHOOL GEARS.
      - **Color Vibe:** Neon Blue, Cyberpunk Cyan, Deep Navy, White accents.
    `;
  } else {
    backgroundVisuals = `
      **THEME: CORPORATE PROFESSIONAL**
      - **Background Elements:** Abstract geometric shapes, fluid gradients, glassmorphism, clean architectural lines.
      - **Vibe:** Trustworthy, Clean, Premium.
    `;
  }

  // Define layout structures to process
  let designPrompt = `
    You are a WORLD-CLASS SENIOR GRAPHIC DESIGNER. Your task is to COMPOSITE a professional event poster.
    
    **DESIGN PRINCIPLES (STRICT):**
    1. **Visual Hierarchy:** Event Title is the King. Speaker is the Queen. Details are the Court.
    2. **Composition:** Use a balanced, grid-based layout. Ensure wide margins (safety zones) around the edges.
    3. **White Space:** Do not clutter. Let the design breathe.
    4. **Text:** ALL TEXT MUST BE IN VIETNAMESE. Font must be Bold, Sans-Serif, Professional.
    
    ${backgroundVisuals}
    
    **NEGATIVE PROMPTS (WHAT TO AVOID):**
    - ${forbiddenVisuals}
    - Do NOT draw the MISA logo by hand. You MUST use the provided logo image.
    - Do NOT change the face of the speaker.
  `;

  // --- BACKGROUND ---
  if (formData.useUploadedBackground && backgroundPart) {
    parts.push(backgroundPart);
    designPrompt += `\n**BACKGROUND SOURCE:** Use Image ${parts.length} as the background base. Layer content on top.`;
  } else {
    designPrompt += `\n**BACKGROUND GENERATION:** Create a background based on the Theme defined above.`;
  }

  // --- HEADER SECTION ---
  let misaLogoRef = "";
  if (defaultLogoPart) {
    parts.push(defaultLogoPart);
    misaLogoRef = `Image ${parts.length}`;
  }

  if (formData.useBrandLogo) {
    if (misaLogoRef) {
      designPrompt += `\n- **Logo 1 (Organizer):** Place ${misaLogoRef} at TOP LEFT on a clean white pill/box background.`;
    }
    // Custom logos if supplied
    for (const logo of logoParts) {
      parts.push(logo);
      designPrompt += `\n- **Logo (Partner/Product):** Place Image ${parts.length} in the top-header banner.`;
    }
  } else {
    if (misaLogoRef) {
      designPrompt += `\n- **PRIMARY LOGO:** Place ${misaLogoRef} prominently at the **TOP CENTER** (or Top Left). 
      **CRITICAL:** The logo must be placed inside a **SOLID WHITE RECTANGLE** to ensure readability against the complex background. Do not blend it multiply.`;
    }
  }

  // Event Title & Type
  designPrompt += `
    \n**HEADLINE SECTION (Top Half):**
    - **Overline (Small):** "${formData.eventType}"
    - **MAIN TITLE (HUGE):** "${formData.eventName.toUpperCase()}"
      - **Effect:** 3D Metallic or Glossy Text effect. High contrast.
      - **Position:** Center or Center-Left alignment.
  `;

  // Time & Location
  const dateTime = `${formData.time} | ${formData.date}`;
  designPrompt += `\n- **Sub-headline:** "${dateTime}" (Clear, bold text).`;

  if (formData.eventFormat === "online") {
    designPrompt += `\n- **Location:** "Hình thức: ${formData.onlinePlatform}" (Add a small Camera/Wifi icon).`;
  } else {
    designPrompt += `\n- **Location:** "${formData.offlineAddress}" (Add a Map Pin icon).`;
  }

  // --- SPEAKER SECTION (THE HERO) ---
  const validSpeakers = formData.speakers.filter((s: any) => s.name.trim() !== "");
  if (validSpeakers.length > 0 && speakerParts.length > 0) {
    designPrompt += `
      \n**SPEAKER SECTION (The "Hero" Visual):**
      - **Layout:** Arrange speaker(s) in the lower half.
      - **Style:** Professional Portrait.
    `;

    for (let i = 0; i < validSpeakers.length; i++) {
      const speaker = validSpeakers[i];
      if (speakerParts[i]) {
        parts.push(speakerParts[i]);
        designPrompt += `
          \n**SPEAKER ${i + 1} (Reference: Image ${parts.length}):**
          - **IDENTITY LOCK:** This is a real person. **YOU MUST PRESERVE THEIR FACE EXACTLY.** Do not generate a random AI person.
          - **COMPOSITION:** Cut out the person from their background. Place them **LARGE** in the design.
          - **SCALE:** The person should occupy at least **40-50% of the poster height**. They should look impressive and authoritative.
          - **Info Box:** Next to or below the person, add a sleek text box containing:
            - NAME: "${speaker.name}" (Bold, Large)
            - TITLE: "${speaker.title}"
            - COMPANY: "${speaker.company}"
        `;

        if (speaker.editPrompt) {
          designPrompt += `\n- **Edit Request:** Use the face from Image ${parts.length}, but change body/clothing to: "${speaker.editPrompt}". Keep the head-to-body ratio realistic.`;
        }
      }
    }
  }

  // --- AGENDA & FOOTER ---
  if (formData.agenda && formData.agenda.length > 0) {
    designPrompt += `\n- **Agenda (Optional Side Column):** If space permits, list: ${formData.agenda
      .map((a: any) => `${a.time}-${a.activity}`)
      .join("; ")}.`;
  }

  // Footer Contact
  const contact = [formData.contactName, formData.contactPhone]
    .filter(Boolean)
    .join(" - ");
  if (contact) {
    designPrompt += `\n- **Footer Bar:** Create a clean bar at the very bottom containing: "Hotline: ${contact}".`;
  }

  // QR Code
  if (formData.includeQrCode && qrCodePart) {
    parts.push(qrCodePart);
    designPrompt += `\n- **QR Code:** Place Image ${parts.length} at Bottom Right. Add text "${formData.qrCta}".`;
  }

  try {
    // 1) Render step with the GPT-3.5 prompt processor engine
    const enginePrompt = `
      You are an expert prompt engineer and senior creative designer.
      Rewrite and enhance the following design blueprint into an extremely rich, detailed visual description prompt (approx. 400-800 words) for a high-quality poster generation model named gemini-3.1-flash-image.
      Focus on gorgeous typography, 3D style effects, sharp contrast, clear Vietnamese text alignment, precise layout layering, color-balanced lighting, and professional placement instructions for logos, speakers and elements.
      Ensure the prompt references any active source images by their relative numbers (Image 1, Image 2, etc.) correctly.

      Design Blueprint:
      ${designPrompt}

      Only return the final enhanced design prompt itself as plain text. Do not wrap in markdown or add introductions.
    `;

    console.log("Generating enhanced prompt via gemini-3.5-flash...");
    const engineResponse = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: enginePrompt,
    });

    const enhancedPrompt = engineResponse.text || designPrompt;
    console.log("Enhanced prompt generated! Length:", enhancedPrompt.length);

    // 2) Generate poster image using the enhanced prompt with robust fallbacks
    let imageUrl = "";
    let detailedErrors: string[] = [];

    // Attempt 1: gemini-3.1-flash-image (High-Quality modern multi-modal image gen/edit)
    try {
      console.log("Generating poster image via gemini-3.1-flash-image...");
      // For general image models, only pass the text prompt and at most ONE starting image (like the uploaded background layout)
      const activeParts: Part[] = [{ text: enhancedPrompt }];
      if (formData.useUploadedBackground && backgroundPart) {
        activeParts.push(backgroundPart);
      }

      const response = await ai.models.generateContent({
        model: "gemini-3.1-flash-image",
        contents: { parts: activeParts },
        config: {
          imageConfig: {
            aspectRatio: formData.aspectRatio || "16:9",
            imageSize: "2K", // Output image 2K high resolution
          },
        },
      });

      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          imageUrl = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
          break;
        }
      }
    } catch (err31: any) {
      console.warn("gemini-3.1-flash-image failed:", err31);
      detailedErrors.push(`gemini-3.1-flash-image error: ${err31.message || err31}`);
    }

    // Attempt 2: gemini-2.5-flash-image (General Image generation/editing fallback)
    if (!imageUrl) {
      try {
        console.log("Fallback 1: Generating poster image via gemini-2.5-flash-image...");
        const activeParts: Part[] = [{ text: enhancedPrompt }];
        if (formData.useUploadedBackground && backgroundPart) {
          activeParts.push(backgroundPart);
        }

        const response = await ai.models.generateContent({
          model: "gemini-2.5-flash-image",
          contents: { parts: activeParts },
          config: {
            imageConfig: {
              aspectRatio: formData.aspectRatio || "16:9",
            },
          },
        });

        for (const part of response.candidates?.[0]?.content?.parts || []) {
          if (part.inlineData) {
            imageUrl = `data:${part.inlineData.mimeType};base64,part.inlineData.data`;
            imageUrl = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
            break;
          }
        }
      } catch (err25: any) {
        console.warn("gemini-2.5-flash-image failed:", err25);
        detailedErrors.push(`gemini-2.5-flash-image error: ${err25.message || err25}`);
      }
    }

    // Attempt 3: imagen-3.0-generate-002 (Golden Standard Google Text-to-Image)
    if (!imageUrl) {
      try {
        console.log("Fallback 2: Generating poster image via imagen-3.0-generate-002...");
        const response = await ai.models.generateImages({
          model: "imagen-3.0-generate-002",
          prompt: enhancedPrompt,
          config: {
            numberOfImages: 1,
            outputMimeType: "image/jpeg",
            aspectRatio: formData.aspectRatio || "16:9",
          },
        });

        if (response.generatedImages?.[0]?.image?.imageBytes) {
          const base64Bytes = response.generatedImages[0].image.imageBytes;
          imageUrl = `data:image/jpeg;base64,${base64Bytes}`;
        }
      } catch (errImagen: any) {
        console.error("imagen-3.0-generate-002 failed:", errImagen);
        detailedErrors.push(`imagen-3.0-generate-002 error: ${errImagen.message || errImagen}`);
        throw new Error(
          `Tất cả các mô hình tạo ảnh đều thất bại.\nChi tiết lỗi:\n- ${detailedErrors.join("\n- ")}`
        );
      }
    }

    if (imageUrl) {
      res.json({ imageUrl });
      return;
    }

    throw new Error("Model failed to output inline image data.");
  } catch (error) {
    console.error("Poster Generation API Error:", error);
    const err = error as any;
    res.status(500).json({
      error: err.stack || err.message || JSON.stringify(err) || "Unknown Poster Generation API Error"
    });
  }
});

// Configure Vite middleware or Static files build
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*all", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server is running on http://localhost:${PORT}`);
  });
}

startServer();
